[package]
name = "cansentinel"
version = "0.1.0"
edition = "2024"

[dependencies]
neli = "0.6.5"
socketcan = "3.5.0"
tokio = { version = "1.0", features = ["rt-multi-thread", "sync", "time", "macros"] }
