[package]
name = "cansentinel"
version = "0.1.0"
edition = "2024"

[dependencies]
neli = "0.6.5"
nix = { version = "0.30.1", features = ["process"] }
socketcan = "3.5.0"
tokio = { version = "1.0", features = ["full"] }
